name: Data ingest
on:
    schedule:
        - cron:  '0 0 * * *'
    workflow_dispatch:
        inputs:
            environment:
                description: 'Environment to push into'
                type: environment
                required: true
                default: dev

run-name: "[${{ inputs.environment }}] Ingest data by @${{ github.actor }}"
jobs:
    ingest-data:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup Python
              uses: actions/setup-python@v5
              with:
                python-version: '3.9'
                cache: 'pip'

            - name: Install dependencies
              run: pip install -r ingest/requirements.txt

            - name: Ingest dataset
              run: python3 ingest/ingest.py

            - name: Upload new data
              uses: Smart-Transportation/push@v1.3
              with:
                github_token: ${{ secrets.GITHUB_TOKEN }}
                message: 'Upload new data ${date}'